# Partie A – Chargement et exploration des données

1. Importer Pandas et charger la feuille « Donnees_Clients » du fichier Excel dans un DataFrame.

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("C:\\Users\\moham\\OneDrive\\Desktop\\Yassine\\TP_Prétraitement_des_données\\jeu_donnees_clients_banque_100_lignes.xlsx")

In [3]:
df

,ID_Client,Age,Revenu_annuel_DH,Solde_DH,Anciennete_mois,Ville,Profession,Niveau_etudes,Satisfaction,Statut
0,C001,41,80000.0,10000.0,43.0,Fès,Indépendant,Bac,Moyenne,Prospect
1,C002,48,112000.0,NaN,8.0,Rabat,Retraité,Master,Faible,Client
2,C003,58,135000.0,11200.0,55.0,Casablanca,Indépendant,Bac,Moyenne,Prospect
3,C004,38,73000.0,3700.0,39.0,Kénitra,Retraité,Licence,Moyenne,Client
4,C005,38,135000.0,8700.0,60.0,Fès,Indépendant,Master,Élevée,Client
...,...,...,...,...,...,...,...,...,...,...
95,C096,32,167000.0,-2800.0,8.0,Tanger,Cadre,Licence,Faible,Client
96,C097,44,26000.0,5100.0,46.0,Casablanca,Étudiant,Master,Très élevée,Client
97,C098,48,86000.0,-2400.0,16.0,Rabat,Fonctionnaire,Licence,Très élevée,Prospect
98,C099,65,90000.0,-2400.0,92.0,Kénitra,Retraité,Master,Moyenne,Prospect
99,C100,36,89000.0,7600.0,41.0,Kénitra,Salarié,Bac,Faible,Prospect

2. Afficher les 10 premières lignes, le nombre de lignes et de colonnes, ainsi que les noms des variables.

In [4]:
df.head(10)

,ID_Client,Age,Revenu_annuel_DH,Solde_DH,Anciennete_mois,Ville,Profession,Niveau_etudes,Satisfaction,Statut
0,C001,41,80000.0,10000.0,43.0,Fès,Indépendant,Bac,Moyenne,Prospect
1,C002,48,112000.0,NaN,8.0,Rabat,Retraité,Master,Faible,Client
2,C003,58,135000.0,11200.0,55.0,Casablanca,Indépendant,Bac,Moyenne,Prospect
3,C004,38,73000.0,3700.0,39.0,Kénitra,Retraité,Licence,Moyenne,Client
4,C005,38,135000.0,8700.0,60.0,Fès,Indépendant,Master,Élevée,Client
5,C006,61,97000.0,5400.0,71.0,Fès,Retraité,Bac,Faible,Client
6,C007,61,80000.0,7000.0,67.0,Témara,Salarié,Master,Très élevée,Client
7,C008,49,100000.0,21600.0,86.0,Marrakech,Salarié,Master,Moyenne,Client
8,C009,65,93000.0,4700.0,107.0,Fès,Salarié,Master,NaN,Prospect
9,C010,48,124000.0,3300.0,13.0,Marrakech,Indépendant,Master,Moyenne,Prospect

In [5]:
df.shape

(100, 10)

In [6]:
df.columns

Index(['ID_Client', 'Age', 'Revenu_annuel_DH', 'Solde_DH', 'Anciennete_mois',
       'Ville', 'Profession', 'Niveau_etudes', 'Satisfaction', 'Statut'],
      dtype='object')

3. Afficher les types des variables et produire un résumé statistique des variables numériques.

In [7]:
df.dtypes

ID_Client            object
Age                   int64
Revenu_annuel_DH    float64
Solde_DH            float64
Anciennete_mois     float64
Ville                object
Profession           object
Niveau_etudes        object
Satisfaction         object
Statut               object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_Client         100 non-null    object
 1   Age               100 non-null    int64
 2   Revenu_annuel_DH  95 non-null     float64
 3   Solde_DH          93 non-null     float64
 4   Anciennete_mois   97 non-null     float64
 5   Ville             97 non-null     object
 6   Profession        98 non-null     object
 7   Niveau_etudes     98 non-null     object
 8   Satisfaction      96 non-null     object
 9   Statut            100 non-null    object
dtypes: float64(3), int64(1), object(6)
memory usage: 7.9+ KB

In [9]:
df.describe()

              Age  Revenu_annuel_DH      Solde_DH  Anciennete_mois
count  100.000000         95.000000     93.000000        97.000000
mean    43.010000      98505.263158   7450.537634        41.855670
std     13.123727      49093.673745   9125.521113        31.626396
min     20.000000      12000.000000  -8900.000000         2.000000
25%     32.000000      65000.000000   1000.000000        17.000000
50%     42.500000      88000.000000   6200.000000        32.000000
75%     53.250000     124000.000000  11200.000000        67.000000
max     65.000000     220000.000000  39800.000000       132.000000

4. Calculer le nombre de valeurs manquantes pour chaque colonne.

In [10]:
df.isna().sum()

ID_Client           0
Age                 0
Revenu_annuel_DH    5
Solde_DH            7
Anciennete_mois     3
Ville               3
Profession          2
Niveau_etudes       2
Satisfaction        4
Statut              0
dtype: int64

5. Classer les variables en quatre groupes : identifiant, numérique, nominale et ordinale. Justifier le classement.

In [11]:
df['Statut'].unique

<bound method Series.unique of 0     Prospect
1       Client
2     Prospect
3       Client
4       Client
        ...
95      Client
96      Client
97    Prospect
98    Prospect
99    Prospect
Name: Statut, Length: 100, dtype: object>

In [12]:
df.columns

Index(['ID_Client', 'Age', 'Revenu_annuel_DH', 'Solde_DH', 'Anciennete_mois',
       'Ville', 'Profession', 'Niveau_etudes', 'Satisfaction', 'Statut'],
      dtype='object')

identifiant:ID_Client.   ||   numérique:Age, Revenu_annuel_DH, Solde_DH, Anciennete_mois.  ||    nominale: Ville, Profession.   ||  ordinale: Niveau_etudes, Satisfaction, Statut

# Partie B – Normalisation Min-Max

1. Sélectionner les variables Age, Revenu_annuel_DH, Solde_DH et Anciennete_mois.

In [13]:
variables_num = ['Age', 'Revenu_annuel_DH', 'Solde_DH', 'Anciennete_mois']
df_num = df[variables_num].copy()

2. Vérifier et traiter les valeurs manquantes de ces variables avant d’appliquer le scaler. Indiquer la méthode 
retenue et la justifier.

In [14]:
df_num.isna().sum()

Age                 0
Revenu_annuel_DH    5
Solde_DH            7
Anciennete_mois     3
dtype: int64

Méthode retenue et justification :Méthode : Imputation par la médiane de chaque colonne.   Justification : La médiane est une mesure robuste insensible aux valeurs extrêmes (outliers) et aux distributions asymétriques, contrairement à la moyenne qui peut être fortement biaisée.

In [15]:
for col in variables_num:
    df_num[col] = df_num[col].fillna(df_num[col].median())

3 . Appliquer MinMaxScaler aux variables numériques sélectionnées.

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_minmax = pd.DataFrame(scaler.fit_transform(df_num), columns=variables_num)
# df_minmax = scaler.fit_transform(df_num)

In [17]:
df_minmax

         Age  Revenu_annuel_DH  Solde_DH  Anciennete_mois
0   0.466667          0.326923  0.388090         0.315385
1   0.622222          0.480769  0.310062         0.046154
2   0.844444          0.591346  0.412731         0.407692
3   0.400000          0.293269  0.258727         0.284615
4   0.400000          0.591346  0.361396         0.446154
..       ...               ...       ...              ...
95  0.266667          0.745192  0.125257         0.046154
96  0.533333          0.067308  0.287474         0.338462
97  0.622222          0.355769  0.133470         0.107692
98  1.000000          0.375000  0.133470         0.692308
99  0.355556          0.370192  0.338809         0.300000

[100 rows x 4 columns]

4 . Afficher les premières lignes du résultat et vérifier les minimums et maximums obtenus.

In [18]:
df_minmax.head()

        Age  Revenu_annuel_DH  Solde_DH  Anciennete_mois
0  0.466667          0.326923  0.388090         0.315385
1  0.622222          0.480769  0.310062         0.046154
2  0.844444          0.591346  0.412731         0.407692
3  0.400000          0.293269  0.258727         0.284615
4  0.400000          0.591346  0.361396         0.446154

In [19]:
df_minmax.min()

Age                 0.0
Revenu_annuel_DH    0.0
Solde_DH            0.0
Anciennete_mois     0.0
dtype: float64

In [20]:
df_minmax.max()

Age                 1.0
Revenu_annuel_DH    1.0
Solde_DH            1.0
Anciennete_mois     1.0
dtype: float64

5 . Expliquer l’effet de la normalisation sur les unités de mesure et sur les valeurs négatives éventuelles.

- Sur les unités de mesure : Supprime toutes les unités (DH, années, mois) pour ramener toutes les caractéristiques sur une même échelle sans unité $[0, 1]$, empêchant une variable ayant de grands chiffres (ex: Revenu_annuel_DH) de dominer le modèle. 
-  Sur les valeurs négatives : Les montants négatifs (par exemple un découvert bancaire dans Solde_DH de $-8900\text{ DH}$) sont transposés et compressés à l'intérieur de l'intervalle $[0, 1]$ (la valeur la plus négative devient $0.0$).

# Partie C – Standardisation

1 . À partir des données numériques préparées, appliquer StandardScaler.

In [21]:
from sklearn.preprocessing import StandardScaler
stand= StandardScaler()

In [22]:
# # # Methode 1:
df_std =pd.DataFrame(stand.fit_transform(df_num), columns=variables_num)

In [23]:
# # # Methode 2:
# df_stand_1 = stand.fit_transform(df_minmax)
# df_stand_1=pd.DataFrame(data=df_stand)

2 . Afficher les premières lignes des variables standardisées.

In [24]:
# # pour methode 1: 
df_std.head()

# # pour methode 2:
# df_stand_1.head()

        Age  Revenu_annuel_DH  Solde_DH  Anciennete_mois
0 -0.153929         -0.377310  0.301072         0.046402
1  0.382143          0.294210 -0.132782        -1.081430
2  1.147960          0.776864  0.438078         0.433088
3 -0.383674         -0.524205 -0.418212        -0.082493
4 -0.383674          0.776864  0.152648         0.594206

3 . Calculer la moyenne et l’écart-type de chaque variable après transformation.

In [25]:
print("Moyennes après transformation :\n", df_std.mean())
print("\nÉcarts-types après transformation :\n", df_std.std(ddof=0))

Moyennes après transformation :
 Age                 1.487699e-16
Revenu_annuel_DH   -8.604228e-18
Solde_DH            1.578598e-17
Anciennete_mois    -7.632783e-17
dtype: float64

Écarts-types après transformation :
 Age                 1.0
Revenu_annuel_DH    1.0
Solde_DH            1.0
Anciennete_mois     1.0
dtype: float64

4 . Comparer les résultats de StandardScaler et de MinMaxScaler.

- MinMaxScaler : Borne rigoureusement les données dans $[0, 1]$. Sensible aux valeurs abracadabrantes/outliers car la présence d'une valeur extrême compresse toutes les autres valeurs courantes dans un sous-intervalle très étroit. 
-  StandardScaler : Centre les données sur $0$ avec un écart-type de $1$. Il n'a pas de limites inférieures ou supérieures fixes et résiste beaucoup mieux aux valeurs aberrantes (outliers)

5 . Citer deux algorithmes ou situations où la mise à l’échelle des variables peut être utile.

- Algorithmes basés sur la distance : $k$-Nearest Neighbors ($k$-NN), $k$-Means, DBSCAN et SVM (Support Vector Machines).  
- Algorithmes basés sur la descente de gradient : Régression Logistique, Réseaux de Neurones / Deep Learning et Régression Linéaire avec régularisation (Lasso/Ridge).

# Partie D – Encodage des variables nominales

1 . Identifier les catégories distinctes de Ville et de Profession.

In [26]:
df.head()

,ID_Client,Age,Revenu_annuel_DH,Solde_DH,Anciennete_mois,Ville,Profession,Niveau_etudes,Satisfaction,Statut
0,C001,41,80000.0,10000.0,43.0,Fès,Indépendant,Bac,Moyenne,Prospect
1,C002,48,112000.0,NaN,8.0,Rabat,Retraité,Master,Faible,Client
2,C003,58,135000.0,11200.0,55.0,Casablanca,Indépendant,Bac,Moyenne,Prospect
3,C004,38,73000.0,3700.0,39.0,Kénitra,Retraité,Licence,Moyenne,Client
4,C005,38,135000.0,8700.0,60.0,Fès,Indépendant,Master,Élevée,Client

In [27]:
print("Villes :", df['Ville'].dropna().unique())
print("Professions :", df['Profession'].dropna().unique())

Villes : ['Fès' 'Rabat' 'Casablanca' 'Kénitra' 'Témara' 'Marrakech' 'Agadir'
 'Tanger']
Professions : ['Indépendant' 'Retraité' 'Salarié' 'Cadre' 'Fonctionnaire' 'Commerçant'
 'Étudiant']

2 . Appliquer OneHotEncoder à ces deux variables.

In [28]:
df.isna().sum()

ID_Client           0
Age                 0
Revenu_annuel_DH    5
Solde_DH            7
Anciennete_mois     3
Ville               3
Profession          2
Niveau_etudes       2
Satisfaction        4
Statut              0
dtype: int64

Remplacement des valeurs manquantes par le mode

In [29]:
df['Ville'] = df['Ville'].fillna(df['Ville'].mode()[0])
df['Profession'] = df['Profession'].fillna(df['Profession'].mode()[0])

methode simple de OneHotEncoder

In [30]:
df_encoded= pd.get_dummies(df[["Ville", "Profession"]],dtype=int)

In [31]:
df_encoded

,Ville_Agadir,Ville_Casablanca,Ville_Fès,Ville_Kénitra,Ville_Marrakech,Ville_Rabat,Ville_Tanger,Ville_Témara,Profession_Cadre,Profession_Commerçant,Profession_Fonctionnaire,Profession_Indépendant,Profession_Retraité,Profession_Salarié,Profession_Étudiant
0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
2,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
4,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
96,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
97,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0
98,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
99,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0

2 éme methode de OneHotEncoder

In [32]:
# from sklearn.preprocessing import OneHotEncoder

# # Remplacement des valeurs manquantes par le mode
# df['Ville'] = df['Ville'].fillna(df['Ville'].mode()[0])
# df['Profession'] = df['Profession'].fillna(df['Profession'].mode()[0])

# ohe = OneHotEncoder(sparse_output=False)
# matrice_ohe = ohe.fit_transform(df[['Ville', 'Profession']])
# cols_ohe = ohe.get_feature_names_out(['Ville', 'Profession'])

# df_ohe = pd.DataFrame(matrice_ohe, columns=cols_ohe)
# df_ohe
# # #  Afficher les noms des colonnes créées et les premières lignes de la matrice encodée. 
# print("Noms des colonnes créées :", cols_ohe)
# print(df_ohe.head())

3 . Afficher les noms des colonnes créées et les premières lignes de la matrice encodée.

In [33]:
print("les noms de colonnes encoder: \n", df_encoded.columns)
print("---------------------------------------------")
print("les 5 premier lignes de data encoder:\n")
df_encoded.head()

les noms de colonnes encoder:
 Index(['Ville_Agadir', 'Ville_Casablanca', 'Ville_Fès', 'Ville_Kénitra',
       'Ville_Marrakech', 'Ville_Rabat', 'Ville_Tanger', 'Ville_Témara',
       'Profession_Cadre', 'Profession_Commerçant', 'Profession_Fonctionnaire',
       'Profession_Indépendant', 'Profession_Retraité', 'Profession_Salarié',
       'Profession_Étudiant'],
      dtype='object')
---------------------------------------------
les 5 premier lignes de data encoder:

,Ville_Agadir,Ville_Casablanca,Ville_Fès,Ville_Kénitra,Ville_Marrakech,Ville_Rabat,Ville_Tanger,Ville_Témara,Profession_Cadre,Profession_Commerçant,Profession_Fonctionnaire,Profession_Indépendant,Profession_Retraité,Profession_Salarié,Profession_Étudiant
0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
2,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
4,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0

4 . Préciser le nombre de nouvelles colonnes générées.

Calcul : $8\text{ (villes)} + 7\text{ (professions)} = 15$ colonnes créées au total.

In [34]:
print("les dimension de data encoder: \n", df_encoded.shape)

les dimension de data encoder:
 (100, 15)

# Partie E – Encodage des variables ordinales

1 . Définir les catégories dans le bon ordre avec OrdinalEncoder.

In [35]:
from sklearn.preprocessing import OrdinalEncoder

# Traitement préalable des valeurs manquantes par le mode
df['Niveau_etudes'] = df['Niveau_etudes'].fillna(df['Niveau_etudes'].mode()[0])
df['Satisfaction'] = df['Satisfaction'].fillna(df['Satisfaction'].mode()[0])

# Ordres respectifs
ordre_etudes = ['Bac', 'Licence', 'Master', 'Doctorat']
ordre_satisfaction = ['Faible', 'Moyenne', 'Élevée', 'Très élevée']

ord_enc = OrdinalEncoder(categories=[ordre_etudes, ordre_satisfaction])

2 . Transformer Niveau_etudes et Satisfaction en valeurs numériques.

In [36]:
matrice_ord = ord_enc.fit_transform(df[['Niveau_etudes', 'Satisfaction']])
df_ord = pd.DataFrame(matrice_ord, columns=['Niveau_etudes_encoded', 'Satisfaction_encoded'])

In [37]:
df_ord['Satisfaction_encoded'].unique()

array([1., 0., 2., 3.])

3 . Afficher les valeurs originales et encodées pour quelques lignes.

In [38]:
comparaison = pd.concat([df[['Niveau_etudes', 'Satisfaction']], df_ord], axis=1)
print(comparaison.head())

  Niveau_etudes Satisfaction  Niveau_etudes_encoded  Satisfaction_encoded
0           Bac      Moyenne                    0.0                   1.0
1        Master       Faible                    2.0                   0.0
2           Bac      Moyenne                    0.0                   1.0
3       Licence      Moyenne                    1.0                   1.0
4        Master       Élevée                    2.0                   2.0

4 . Expliquer la différence entre un encodage nominal et un encodage ordinal.

- Encodage Nominal (One-Hot Encoding) : Utilisé pour des variables sans ordre hiérarchique (ex: Ville). Il crée $N$ colonnes binaires ($0/1$) afin de ne pas introduire de relation mathématique d'ordre inexistante entre les catégories.  
- Encodage Ordinal : Utilisé quand un ordre ou un rang logique existe (ex: Niveau d'études). Il convertit les catégories en un seul vecteur d'entiers séquentiels ($0, 1, 2, 3...$), préservant ainsi la hiérarchie tout en conservant une seule colonne.

# Partie F – Synthèse et analyse

1 . Construire un tableau récapitulatif indiquant, pour chaque variable, son type et la transformation appliquée.

In [39]:
df.columns

Index(['ID_Client', 'Age', 'Revenu_annuel_DH', 'Solde_DH', 'Anciennete_mois',
       'Ville', 'Profession', 'Niveau_etudes', 'Satisfaction', 'Statut'],
      dtype='object')

In [40]:
# |Variable         | Type de variable            | Transformation / Traitement appliqué               |
# |-----------------|-----------------------------|----------------------------------------------------|
# |ID_Client        | Identifiant	              | Exclus / Supprimé du modélisation                  |
# |Age	Numérique | continue       	    	      | Imputation Médiane + Normalisation/Standardisation |
# |Revenu_annuel_DH | Numérique continue		  | Imputation Médiane + Normalisation/Standardisation |
# |Solde_DH         | Numérique continue		  | Imputation Médiane + Normalisation/Standardisation |
# |Anciennete_mois  | Numérique continue		  | Imputation Médiane + Normalisation/Standardisation |
# |Ville	        | Qualitatives Nominale	      | Imputation Mode + One-Hot Encoding                 | 
# |Profession       | Qualitatives Nominale	      | Imputation Mode + One-Hot Encoding                 | 
# |Niveau_etudes	| Qualitatives Ordinale	      | Imputation Mode + Ordinal Encoding                 | 
# |Satisfaction     | Qualitatives Ordinale	      | Imputation Mode + Ordinal Encoding                 | 
# |Statut	        | Qualitatives Cible (Target) | Label Encoding (0/1)                               | 
# |-----------------|-----------------------------|----------------------------------------------------|

2 . Comparer le nombre de colonnes avant et après One-Hot Encoding.

- Avant One-Hot Encoding : $2$ colonnes (Ville, Profession).   
- Après One-Hot Encoding : $15$ colonnes binaires générées

3 . Expliquer pourquoi l’identifiant ID_Client ne doit généralement pas être utilisé comme variable explicative.

est une clé primaire / identifiant unique assigné arbitrairement. Il n'a aucune valeur prédictive ni corrélation causale avec le comportement bancaire du client. L'inclure provoquerait du surapprentissage (overfitting), car le modèle apprendrait par cœur les identifiants au lieu de généraliser sur les vrais motifs

4 . Expliquer pourquoi les paramètres des transformations doivent être calculés sur les données d’entraînement 
uniquement lorsqu’on construit un modèle prédictif.

Afin d'éviter la fuite de données (Data Leakage). Les statistiques (moyenne, écart-type, $\min$, $\max$, médiane) doivent être calculées uniquement sur le jeu de données d'entraînement (Train), puis appliquées telles quelles sur le jeu de test (Test). Cela garantit que le modèle est évalué dans des conditions réelles sur des données inédites qu'il n'a jamais observées à l'avance.

5 . Proposer un ordre logique des opérations à effectuer avant d’entraîner un modèle de Machine Learning.

- Séparation des données : Diviser en jeu d'entraînement (X_train, y_train) et jeu de test (X_test,y_test).  
- Nettoyage : Imputation des valeurs manquantes (ajustée sur Train).  
- Encodage catégoriel : Application de l'Ordinal Encoding et du One-Hot Encoding. 
- Mise à l'échelle : Application de la Normalisation ou Standardisation sur les variables numériques.   
- Entraînement du modèle : Ajustement de l'algorithme de Machine Learning sur les données prétraitées

10. Livrables 
- Un notebook ou un script Python commenté. ✔️✅
- Un tableau de synthèse des variables et des méthodes de prétraitement. ✔️✅
- Un court paragraphe comparant normalisation et standardisation. ✔️✅
- Les résultats des encodages nominal et ordinal. ✔️✅